[]{#sessions}

# I kursuse sisu

## Arvuhulgad. Avaldised. Võrrandid

### Õpitulemused

\multicolsbegin

Kursuse lõpus õpilane:

1. leiab hulkade ühendi, ühisosa ja antud hulga osahulga;
2. eristab arvuhulki N; Z; Q; I ja R, selgitab nende kuuluvusseoseid;
3. märgib arvteljel reaalarvude piirkondi;
4. eristab võrdust, samasust, võrrandit ja võrratust;
5. lahendab ühe tundmatuga lineaar- ja ruutvõrrandeid ning -võrratusi, samuti lihtsamaid
murdvõrrandeid (maksimaalselt 2 murdu) ning ühe tundmatuga lineaarvõrratuste süsteeme;
6. sooritab tehteid astmete ja juurtega (teine kuni neljas juur), teisendades viimased
ratsionaalarvulise astendajaga astmeteks;
7. teisendab lihtsamaid (kaks tehet ja sulud) ratsionaal- ja irratsionaalavaldisi;
8. lahendab lihtsamaid reaalelulise kontekstiga probleeme võrrandite ja võrrandisüsteemide
abil.[@gmnaasiumi].

\multicolsend

## Kalender

### 2024-9-10

Kaardistasime keeled histogrammi. Tutvustasin hulgateooriat.

Osalesid... paberil kirjas 13 nime.

### 2024-9-10

Tutvustasin arvude hulki ja harjutasime arvude liigitamist.

### 2024-9-11

Kaardistasime keeled histogrammi. Tutvustasin hulgateooriat.

Osalesid Artemi Dudkin, Marija Runjantseva, Uljana Soonvald, Andrea Malinina, Sofja Danilova, vanja fabrichnikov, jegor barinov, Ilja Dudkin, Alisa Абдукаримова, Evelina Bržezitskaja, DANIIL MATVEER, Edgar Bartirov, daniil baskirov, Georgiy Sidorov, Sasha Sumakok, jegor krištal, albert baikov, Valerija Brijankijeva, Emilia Danilova, Lilia Drekhova, Aleksei Baguev, МАКСИМ UJOVENKO, VERONIKA ŠUMILINA.

### 2024-9-11

Tutvustasin arvude hulki.

### 2024-9-11

Harjutasime arvude liigitamist.

10A hinded esimese õpiväljundi saavutatuse kohta:

VERONIKA ŠUMILINA: 3,
МАКСИМ UJOVENKO: 2,
Aleksei Baguev: 2,
Lilia Drekhova: 2,
Emilia Danilova: 2,
Valerija Brjakkijeva: 3,
albert baikov: 4,
Artemi Dudkin: 2,
jegor krištal: 3,
Sasha Sumakok: 3,
Georgiy Sidorov: 3,
daniil baskirov: 4,
Edgar Bartirov: 4,
DANIIL MATVEER: 4,
Evelina Bržezitskaja: 5,
Alisa Абдукаримова: 1,
Ilja Dudkin: 5,
jegor barinov: 4,
vanja fabrichnikov: 5,
Sofja Danilova: 2,
Andrea Malinina: 4,
Uljana Soonvald: 4,
Marija Runjantseva: 2.

### 2024-9-11

Kaardistasime keeled histogrammi. Tutvustasin hulgateooriat.

Osalesid vlada Massalova, Alisa Mazanova, ivan Stulov, Margarita Fjodorova, Lera Fedorova, danil kaskirov, Jegor Jelutimov, Aleksndr Marev, arina orlova, Артем Dmitriiev, Viktoriia Barabanova, Veera Kirillova, Jana Katajeva, Skantseva Sofia, Veronika Aleksandrova, Darina Volkova, sonja seliverstova, Svetlana Antonen, Anna Ivanova, Nastja Demntjeva, Alesja Jakovleva, Kristina golubeva, Anna Simonova.

Esimese õpitulemuse 10F hinded:

Anna Simonova: 5,
Kristina golubeva: 3,
Alesja Jakovleva: 3,
Nastja Demntjeva: 2,
Anna Ivanova: 2,
Svetlana Antonen: 2,
sonja seliverstova: 2,
Darina Volkova: 2,
Veronika Aleksandrova: 2,
Skantseva Sofia: 3,
Jana Katajeva: 2,
Veera Kirillova: 2,
Viktoriia Barabanova: 2,
Артем Dmitriiev: 2,
arina orlova: 2,
Aleksndr Marev: 2,
Jegor Jelutimov: 3,
danil kaskirov: 3,
Lera Fedorova: 3,
Margarita Fjodorova: 2,
ivan Stulov: 4,
Alisa Mazanova: 3,
vlada Massalova: 2.

### 2024-9-12

Lahendasime hulkade ühendi ja ühisosa ülesandeid. Näitasin, mida tähendab elemendi kuuluvus ning harjutasime seda. Näitasin, mida tähendavad osahulgad ja hulkade vahe ning harjutasime ka nende kasutamist.

Osalesid Anna Simonova, ...paberitel

### 2024-9-12

Käsitlesime naturaal- ja täisarvude hulki.

Hinded õpiväljundi 1 kohta:
Anna Luomova: 3,
Andrei Kolotkov: 3,
Daniil Koskirov: 2,
Jana Katajeva: 5,
Lera Fedorova: 4,
Kristina Golubeva: 3,
Anjuta Vorobjova: 5,
Дорин Савельев: 5,
Ivan Mištšenko: 5,
Vlada: 2,
Alisa: 1,
Sirotina Nelli: 3,
sonja pseliverstova: 4,
Kristina Jurma: 4,
Irina Kosatševa: 3,
ALina Chepkasova: 2,
Sveta: 2,
Margarita: 2,
Dorin: 1.

### 2024-9-12

Harjutasime hulkade ühisosa ja ühendi kirjutamist ja visandamist. Tutvustasin elemendi kuuluvust hulka, samuti osahulga sümbolite kasutamist ning tegime nende kohta harjutusi. Lõpuks testisin õpilasi esimese õpiväljundi saavutatuse suhtes.

Esimese õpitulemuse 10B rühma õpilaste saavutamine:

Jaroslav Andrejev: 3,
Nickita Serdiuk: 3,
Artjom Saharov: 2,
Maksim Tolmatsjov: 4,
Daniil Petrauskas: 3,
Ruslan zverev: 3,
Elizaveta Kapitonova: 2,
Ksenija Ignatjeva: 3,
Erik Kapinski: 3,
virko Boitrov: 3.

### 2024-9-17

Lahendasime tahvlile eelmise korra testi ülesandeid.

### 2024-9-17

Tegin lehe https://www.math.cmu.edu/~bkell/21110-2010s/sets.html#:~:text=The%20objects%20in%20a%20set,%2C%20variables%2C%20or%20geometric%20points. abil uue ülevaate hulgateooriast jõudes hulkade erinevuseni. Testisin õpilaste teadmisi-oskusi esimese kahe õpiväljundi osas:
ERik: 1: 2, 2: 4,
JaRoslav: 1: 3, 2: 4,
Nick Serdiuk: 1: 1, 2: 3,
Milana Domožakova: 1: 2, 2: 4,
MakSiM Tolmatsjov: 1: 1, 2: 4,
Daniil: 1:1, 2: 3,
ViRKO.: 1: 1, 2: 4.


Elizaveta Kapitonova oli ka kohal.

Koju: Veelmaa kogumikust 2.

### 2024-9-18

Harjutasime nimede põhjal hulkade ülesande lahendamist: ühend, ühisosa, Venni diagrammid, kuuluvus, osahulk. Tuletasin kompaktselt meelde, mis on ühend ja ühisosa.

### 2024-9-18

Tuletasin kompaktselt meelde osahulga mõiste. Näitasin allikast https://www.math.cmu.edu/~bkell/21110-2010s/sets.html kuni kardinaalarvuni.

### 2024-9-18

Testisime õpilaste teadmisi-oskusi esimese kahe õpiväljundi suhtes:
Marija Rumjantseva: 1: 1, 2: 1,
Artemi Dudkin: 1: 1, 2: 1,
DANiiL MATVeeV: 1: 2, 2: 2,
Edgar Bantirov: 1: 2, 2: 2,
Sumarok Sasha: 1: 2, 2: 2,
Ilja Dudkin: 1: 2, 2: 2,
Valerija Brjakkijeva: 1: 2, 2: 2,
Lilia Drekohva: 1: 2, 2: 2,
ALiSA: 1: 2, 2: 2,
Emilia: 1: 2, 2: 2,
Anna Cherenlova: 1: 2, 2: 2,
Albert Baikov: 1: 2, 2: 2,
Aleksei Bagaev: 1: 2, 2: 2,
udovenko максим: 1: 2, 2: 3,
Ivan Fabrichnikov: 1: 1, 2: 2,
PAVel Plesnev: 1: 1, 2: 2,
Jergor Krištal: 1: 2, 2: 2,
Jegor Burnov: 1: 3, 2: 3,
Danlil Baskirov: 1: 2, 2: 4,
Alina Võssotskaja: 1: 3, 2: 2,
Sofja: 1: 3, 2: 3,
Andrea: 1: 2, 2: 2,
Liliana: 1: 2, 2: 2,
Marja Jurna: 1: 2, 2: 2.

### 2024-9-18

Harjutasime eelmise korra testi ülesannete lahendmist: nimede ühisosa, ühend, elemendi kuuluvus, Venni diagrammid. Tegime uue testi: arvu kuuluvus, seosed arvuhulkade vahel tekstina ja diagrammidena, arvu kuuluvus nime tähtede hulka, seega kaks esimest õpiväljundit:

Jegor Jelvkimov: 1: 2, 2: 3,
Morocov Aleksandra: 1: 2, 2: 3,
Sirotina Nelli: 1: 3, 2: 3,
Drlova Arina: 1: 2, 2:3,
Alisa: 1: 3, 2:2,
vlada: 1: 3, 2:2,
Darin: 1: 2, 2: 3,
MARGiT: 1: 5, 2: 5,
Svetlana Antonen: 1: 2, 2: 3,
Anna Simanova: 1:1, 2:2,
Lera Fedorova: 1: 1, 2: 2.

### 2024-9-19

Lahendasime läbi viimase testi ülesandeid. Tegin kompaktse ülevaate hulgateooria osadest nagu ühend, ühisosa ja alamhulk.

### 2024-9-19

Tegin kompaktse ülevaate arvuhulkadest. Tutvustasin ükshaaval hulgateooria osi ja jõudsime allika https://www.math.cmu.edu/~bkell/21110-2010s/sets.html abil hulkadeni hulkades.

Testisime õpilaste teadmisi-oskusi kahe esimese õpiväljundi osas:
Aptem Dmitpiiev: 1: 2, 2: 2,
Margarita Fjodorova: 1: 3, 2: 2,
Ivan Stulov: 1: 2, 2: 2,
Sirotina Nelli: 1: 1, 2: 1,
Veera Kirillova: 1: 2, 2: 2,
Svetlana Antonen: 1: 1, 2: 1,
Daniil Koskirov: 1: 2, 2: 1,
Alesja Jakovleva: 1: 1, 2: 1,
Sonja Seliverstova: 1: 2, 2: 2,
Arina: 1: 1, 2: 1,
Jana Katajeva: 1: 1, 2: 1,
Kristina Golubeva: 1: 2, 2: 2,
Anna Simanova: 1: 2, 2: 2,
Nastja: 1: 1, 2: 1,
Darin: 1: 2, 2: 1,
Andrei KoLOTKOV: 1: 1, 2: 1,
Dorin: 1: 1, 1: 1,
Jana Jürna: 1: 1, 2: 1,
Kristina Jurna: 1: 1, 2: 1,
Alisa: 1: 1, 2: 1,
Vlada Massalova: 1: 1, 2: 1.

### 2024-9-19

Selgitasin hindamissüsteemi. Jätsin koju lahendada testülesanded:

### 2024-9-24

Näitasin, kuidas viimase testi ülesandeid lahendada ja õpilane lahendas ka. Muu õpilane proovis uuesti kõik läbi teiste sisenditega ja tegi Venni diagrammid ka uuesti.

### 2024-9-24

Selgitasin, kuidas sulge kasutada määramaks tehete järjekorda. Tegime uue testi:
Jaroslav Andrejev: 1: 5, 2: 3,
Maksim Tolmatsjov: 1: 5, 2: 4,
Serdiuk Mykyta: 1: 2, 2: 5,
Virko Boitsov: 1: 2, 2: 1,
Ksenija Ignatjeva: 1: 5, 2: 5,
Elizaveta Kafitonova: 1: 5, 2: 2.

Esimese kahe õpiväljundi eelmise korra testi ülesanded lahendasin õpilastele ühe variandina. Õpilane minu abiga tegi seda ka. Seejärel andsin neile järgmise testi sooritada, aga seekord koju, nii et selle järgi saan teada, kes kohal oli:
nikita,
elizaveta,
Virko Boitsov: 1: 2, 2: 3,
Maksim Tolmatsjov: 1: 2, 2: 3,
Jaroslav Andejv: 1: 4, 2: 3.

### 2024-9-25

Näitasin korra ette, kuidas viimase testi ülesandeid lahendada. Seejärel tegi üks õpilane protsessi läbi.

### 2024-9-25

Tuletasime hulgaoperatsioone meelde alates hulga suurusest kuni tehete järjekorrani lehel https://www.math.cmu.edu/~bkell/21110-2010s/sets.html

### 2024-9-25

Käsitlesime Venni diagramme kuni esimeste erinevusteni samal lehel. Testisime:
DANIILMATVeeV: 1: 5, 2: 5,
aRTEMI dUDKIN: 1: 1, 2: 1,
Bankirov Edgar: 1: 5, 2: 5,
Evelina Bržezitskaya: 1: 3, 2: 4,
Ilja Dudkin: 1: 5, 2: 4,
Danlll Basknlov: 1: 5, 2: 3,
Alina Võssotskaja: 1: 4, 2: 5,
Valerija Brjakkkjeva: 1: 5, 2: 5,
Marja JurNA: 1: 5, 2: 2,
Sumarok Aleksandra: 1: 4, 2: 3,
Ivan Fabrichnikov: 1: 5, 2: 5,
Jegor Barinov: 1: 3, 2: 5.

### 2024-9-25

Näitasin eelmise testi ülesande ühe võimaliku lahenduse. Üks õpilane tegi tahvlile oma lahenduse. Testisime:
Leila Mihailova: 1: 4, 2: 3,
Daniil Koškirov: 1: 5, 2: 5,
Veera Kirillova: 1: 5, 2: 5,
Jegor Jelugemov: 1: 4, 2: 5,
Kristina Golubeva: 1: 5, 2: 3,
Alisa Mazanova: 1: 5, 2: 5,
Lera Fedorova: 1: 4, 2: 3,
Anna Simonova: 1: 3, 2: 1,
Sonja Seliverstova: 1: 5, 2: 3,
Vladislava Massalova: 1: 5, 2: 5,
Alesja Jakovleva: 1: 5, 2: 5.

### 2024-9-26

Käsitlesime hulgateooria osi: alamhulgad, arvuhulgad, hulga koostis, hulgatehted, täiendhulk.

### 2024-9-26

Käsitlesime hulgateooria osi: Venni diagrammid. Lahendasime https://www.math.cmu.edu/~bkell/21110-2010s/sets.html esimese küsimuse positiivsete paarisarvude hulga kohta. Tegime testi esimese kahe õpiväljundi kohta:
